image: gitlab.enterpriselab.ch:4567/abiz-lab/gitlab-ci-agents/docker:stable

services:
  - docker:dind

stages:
  - build

build:
  stage: build
  script:
    - docker build -t fl -f Dockerfile.gpu .

