stages:
  - test

test:
  stage: test
  image: continuumio/miniconda
  script:
    - conda init bash
    - source ~/.bashrc
    - conda envs create -f environment.yml
    - conda activate flatland-rl
    - bash flatlander/test/test.sh
