name: flatland-rl
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex
  - binutils_impl_linux-64
  - binutils_linux-64
  - gcc_impl_linux-64
  - gcc_linux-64
  - glib
  - icu
  - python=3.6.8
  - pip:
    - pyhumps==1.3.1
    - ray[rllib]==1.0.0
    - redis==3.3.2
    - tensorflow_gpu==2.3.0
    - tensorflow-estimator==2.3.0
    - tqdm==4.50.2
    - flatland-rl==2.2.2
    - torch==1.6.0
