name: flatland-rl
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex
  - binutils_impl_linux-64
  - binutils_linux-64
  - gcc_impl_linux-64
  - gcc_linux-64
  - glib
  - icu
  - python=3.7.5
  - pip
