env: flatland_sparse
num_workers: 0
num_envs_per_worker: 1
num_gpus: 0

no_done_at_end: True

learning_starts: 1000
train_batch_size: 512
rollout_fragment_length: 50
target_network_update_freq: 1000
timesteps_per_iteration: 1000
lr: 0.001

env_config:
    n_agents: 5
    observation: tree
    observation_config:
        max_depth: 2
        shortest_path_max_depth: 100
        concat_agent_id: True

    generator: sparse_rail_generator
    generator_config: small_v0

    regenerate_rail_on_reset: False
    regenerate_schedule_on_reset: False

    wandb:
        project: flatland-finetuning
        entity: wullli
        tags: ["small_v0", "tree_obs", "apex", "global_reward"]

model:
    fcnet_activation: relu
    fcnet_hiddens: [256, 256, 256]
    vf_share_layers: True