hierarchical-flatland-sparse-small-tree_obs-robust-fc-apex:
    run: SAC
    env: flatland_sparse_hierarchical
    stop:
        timesteps_total: 15000000
    checkpoint_freq: 1
    checkpoint_at_end: True
    keep_checkpoints_num: 20
    checkpoint_score_attr: episode_reward_mean
    num_samples: 1
    config:
        num_workers: 7
        num_envs_per_worker: 5
        num_gpus: 0

        lr: 0.0001

        normalize_actions: False

        env_config:
            number_of_agents: 5
            observation: combined
            observation_config:
                simple_meta:
                shortest_path:

            gym_env: robust

            generator: sparse_rail_generator
            generator_config: small_v0_malf

            wandb:
                project: flatland
                entity: wullli
                tags: ["small_v0", "apex", "tree", "robust"]

        model:
            fcnet_activation: relu
            fcnet_hiddens: [256, 256, 256]
            vf_share_layers: True  # False


