env: flatland_sparse
num_workers: 4
num_envs_per_worker: 1
num_gpus: 1

env_config:
    observation: tree
    observation_config:
        max_depth: 2
        shortest_path_max_depth: 30

    generator: sparse_rail_generator
    generator_config: small_v0

    regenerate_rail_on_reset: False
    regenerate_schedule_on_reset: False

    global_reward: True

model:
    fcnet_activation: relu
    fcnet_hiddens: [256, 256, 256]
    vf_share_layers: True


