env: flatland_sparse
num_workers: 0
num_envs_per_worker: 1
num_gpus: 1

no_done_at_end: True

learning_starts: 2000
target_network_update_freq: 1000
timesteps_per_iteration: 1000

lr: 0.0001

exploration_config:
   epsilon_timesteps: 10000
   initial_epsilon: 0.1
   final_epsilon: 0.05

env_config:
    observation: tree
    observation_config:
        max_depth: 2
        shortest_path_max_depth: 30
        concat_status: True

    gym_env: sequential
    allow_noop: False

    generator: sparse_rail_generator
    generator_config: small_v0_static

model:
    fcnet_activation: relu
    fcnet_hiddens: [256, 256, 256]
    vf_share_layers: True