env: flatland_sparse
num_workers: 0
num_envs_per_worker: 0
num_gpus: 0

gamma: 0.99

clip_rewards: False
vf_clip_param: 500.0
entropy_coeff: 0.01
# effective batch_size: train_batch_size * num_agents_in_each_environment [5, 10]
# see https://github.com/ray-project/ray/issues/4628
train_batch_size: 1000  # 5000
rollout_fragment_length: 50  # 100
sgd_minibatch_size: 100  # 500
vf_share_layers: False

env_config:
    observation: fixed_tree
    observation_config:
        max_depth: 2
        shortest_path_max_depth: 30
        small_tree: False

    generator: sparse_rail_generator
    generator_config: small_v0

    wandb:
        project: flatland
        entity: wullli
        tags: ["ppo", "small_v0", "fixed", "tree", "transformer", "custom"]

model:
    custom_model: fixed_tree_transformer
    custom_options:
        warmup_steps: 100000
        n_features_per_node: 11
        tree_depth: 2
        transformer:
            use_cnn_decoding: False
            policy_layers:
                - 512
                - 512
                - 512
            value_layers:
                - 512
                - 512
                - 512
            encoder_layer_neurons: 2048
            num_encoder_layers: 2
            num_heads: 11
            dropout_rate: 0.1