env: flatland_sparse
num_workers: 0
num_envs_per_worker: 0
num_gpus: 0

buffer_size: 100000
lr: 0.0002

exploration_config:
    type: PerWorkerEpsilonGreedy
    initial_epsilon: 1.0
    final_epsilon: 0.02
    epsilon_timesteps: 50000

env_config:
    observation: tree
    observation_config:
        max_depth: 2
        shortest_path_max_depth: 30
        concat_agent_id: True
        concat_status: True
        predictor: custom

    gym_env: robust

    generator: sparse_rail_generator
    generator_config: small_v0_malf

    wandb:
        project: flatland
        entity: wullli
        tags: ["small_v0", "apex", "tree", "robust"]

model:
    fcnet_activation: relu
    fcnet_hiddens: [256, 256, 256]
    vf_share_layers: True  # False


