env: flatland_sparse_scaling

num_workers: 1
num_envs_per_worker: 1
num_gpus: 0

gamma: 0.9999

clip_rewards: False
vf_clip_param: 500.0
entropy_coeff: 0.01
# effective batch_size: train_batch_size * num_agents_in_each_environment [5, 10]
# see https://github.com/ray-project/ray/issues/4628
train_batch_size: 1000  # 5000
rollout_fragment_length: 50  # 100
sgd_minibatch_size: 100  # 500
vf_share_layers: False

env_config:
    observation: fixed_tree
    observation_config:
        max_depth: 2
        shortest_path_max_depth: 30
        small_tree: False

    generator: sparse_rail_generator
    generator_config: medium_scaling_v0

    add_agent_interval: 5000 # beware of the n_envs and number workers
    interval_growth_rate: 1.25
    max_agents: 10

    wandb:
        project: flatland
        entity: wullli
        tags: ["ppo", "medium_scaling_v0", "fixed", "tree", "transformer", "custom"]

model:
    custom_model: fixed_tree_transformer
    custom_model_config:
        warmup_steps: 50000
        transformer:
            use_cnn_decoding: False
            policy_layers:
                - 512
                - 512
                - 512
            value_layers:
                - 512
                - 512
                - 512
            encoder_layer_neurons: 2048
            num_encoder_layers: 2
            num_heads: 11
            dropout_rate: 0.1